/* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Other/SQLTemplate.sql to edit this template
 */
/**
 * Author:  asmuammal
 * Created: Sep 29, 2023
 */

-- Insert data for Provinsi
INSERT INTO formasi (provinsi_id, kodeSatker, namaSatuankerja)
VALUES
INSERT INTO provinsi (kodeProvinsi, namaProvinsi)
VALUES 
    ('11', 'Aceh'),
    ('12', 'Sumatera Utara'),
    ('13', 'Sumatera Barat'),
    ('14', 'Riau'),
    ('15', 'Jambi'),
    ('16', 'Sumatera Selatan'),
    ('17', 'Bengkulu'),
    ('18', 'Lampung'),
    ('19', 'Kep. Bangka Belitung'),
    ('21', 'Kep. Riau'),
    ('31', 'Dki Jakarta'),
    ('32', 'Jawa Barat'),
    ('33', 'Jawa Tengah'),
    ('34', 'Di Yogyakarta'),
    ('35', 'Jawa Timur'),
    ('36', 'Banten'),
    ('51', 'Bali'),
    ('52', 'Nusa Tenggara Barat'),
    ('53', 'Nusa Tenggara Timur'),
    ('61', 'Kalimantan Barat'),
    ('62', 'Kalimantan Tengah'),
    ('63', 'Kalimantan Selatan'),
    ('64', 'Kalimantan Timur'),
    ('65', 'Kalimantan Utara'),
    ('71', 'Sulawesi Utara'),
    ('72', 'Sulawesi Tengah'),
    ('73', 'Sulawesi Selatan'),
    ('74', 'Sulawesi Tenggara'),
    ('75', 'Gorontalo'),
    ('76', 'Sulawesi Barat'),
    ('81', 'Maluku'),
    ('82', 'Maluku Utara'),
    ('91', 'Papua Barat'),
    ('94', 'Papua');

-- Insert data for Formasi

INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('1', '1100', 'BPS Provinsi Aceh');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('1', '1101', 'BPS Kabupaten Simeulue');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('1', '1102', 'BPS Kabupaten Aceh Singkil');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('1', '1103', 'BPS Kabupaten Aceh Selatan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('1', '1104', 'BPS Kabupaten Aceh Tenggara');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('1', '1105', 'BPS Kabupaten Aceh Timur');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('1', '1106', 'BPS Kabupaten Aceh Tengah');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('1', '1107', 'BPS Kabupaten Aceh Barat');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('1', '1108', 'BPS Kabupaten Aceh Besar');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('1', '1109', 'BPS Kabupaten Pidie');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('1', '1110', 'BPS Kabupaten Bireuen');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('1', '1111', 'BPS Kabupaten Aceh Utara');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('1', '1112', 'BPS Kabupaten Aceh Barat Daya');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('1', '1113', 'BPS Kabupaten Gayo Lues');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('1', '1114', 'BPS Kabupaten Aceh Tamiang');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('1', '1115', 'BPS Kabupaten Nagan Raya');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('1', '1116', 'BPS Kabupaten Aceh Jaya');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('1', '1117', 'BPS Kabupaten Bener Meriah');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('1', '1118', 'BPS Kabupaten Pidie Jaya');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('1', '1171', 'BPS Kota Banda Aceh');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('1', '1172', 'BPS Kota Sabang');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('1', '1173', 'BPS Kota Langsa');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('1', '1174', 'BPS Kota Lhokseumawe');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('1', '1175', 'BPS Kota Subulussalam');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('2', '1200', 'BPS Provinsi Sumatera Utara');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('2', '1201', 'BPS Kabupaten Nias');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('2', '1202', 'BPS Kabupaten Mandailing Natal');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('2', '1203', 'BPS Kabupaten Tapanuli Selatan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('2', '1204', 'BPS Kabupaten Tapanuli Tengah');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('2', '1205', 'BPS Kabupaten Tapanuli Utara');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('2', '1206', 'BPS Kabupaten Toba Samosir');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('2', '1207', 'BPS Kabupaten Labuhan Batu');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('2', '1208', 'BPS Kabupaten Asahan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('2', '1209', 'BPS Kabupaten Simalungun');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('2', '1210', 'BPS Kabupaten Dairi');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('2', '1211', 'BPS Kabupaten Karo');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('2', '1212', 'BPS Kabupaten Deli Serdang');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('2', '1213', 'BPS Kabupaten Langkat');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('2', '1214', 'BPS Kabupaten Nias Selatan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('2', '1215', 'BPS Kabupaten Humbang Hasundutan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('2', '1216', 'BPS Kabupaten Pakpak Bharat');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('2', '1217', 'BPS Kabupaten Samosir');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('2', '1218', 'BPS Kabupaten Serdang Bedagai');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('2', '1219', 'BPS Kabupaten Batu Bara');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('2', '1220', 'BPS Kabupaten Padang Lawas Utara');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('2', '1221', 'BPS Kabupaten Padang Lawas');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('2', '1222', 'BPS Kabupaten Labuhan Batu Selatan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('2', '1223', 'BPS Kabupaten Labuhan Batu Utara');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('2', '1224', 'BPS Kabupaten Nias Utara');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('2', '1225', 'BPS Kabupaten Nias Barat');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('2', '1271', 'BPS Kota Sibolga');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('2', '1272', 'BPS Kota Tanjung Balai');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('2', '1273', 'BPS Kota Pematang Siantar');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('2', '1274', 'BPS Kota Tebing Tinggi');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('2', '1275', 'BPS Kota Medan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('2', '1276', 'BPS Kota Binjai');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('2', '1277', 'BPS Kota Padangsidimpuan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('2', '1278', 'BPS Kota Gunungsitoli');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('3', '1300', 'BPS Provinsi Sumatera Barat');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('3', '1301', 'BPS Kabupaten Kepulauan Mentawai');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('3', '1302', 'BPS Kabupaten Pesisir Selatan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('3', '1303', 'BPS Kabupaten Solok');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('3', '1304', 'BPS Kabupaten Sijunjung');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('3', '1305', 'BPS Kabupaten Tanah Datar');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('3', '1306', 'BPS Kabupaten Padang Pariaman');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('3', '1307', 'BPS Kabupaten Agam');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('3', '1308', 'BPS Kabupaten Lima Puluh Kota');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('3', '1309', 'BPS Kabupaten Pasaman');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('3', '1310', 'BPS Kabupaten Solok Selatan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('3', '1311', 'BPS Kabupaten Dharmasraya');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('3', '1312', 'BPS Kabupaten Pasaman Barat');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('3', '1371', 'BPS Kota Padang');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('3', '1372', 'BPS Kota Solok');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('3', '1373', 'BPS Kota Sawah Lunto');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('3', '1374', 'BPS Kota Padang Panjang');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('3', '1375', 'BPS Kota Bukittinggi');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('3', '1376', 'BPS Kota Payakumbuh');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('3', '1377', 'BPS Kota Pariaman');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('4', '1400', 'BPS Provinsi Riau');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('4', '1401', 'BPS Kabupaten Kuantan Singingi');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('4', '1402', 'BPS Kabupaten Indragiri Hulu');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('4', '1403', 'BPS Kabupaten Indragiri Hilir');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('4', '1404', 'BPS Kabupaten Pelalawan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('4', '1405', 'BPS Kabupaten Siak');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('4', '1406', 'BPS Kabupaten Kampar');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('4', '1407', 'BPS Kabupaten Rokan Hulu');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('4', '1408', 'BPS Kabupaten Bengkalis');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('4', '1409', 'BPS Kabupaten Rokan Hilir');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('4', '1410', 'BPS Kabupaten Kepulauan Meranti');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('4', '1471', 'BPS Kota Pekanbaru');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('4', '1473', 'BPS Kota Dumai');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('5', '1500', 'BPS Provinsi Jambi');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('5', '1501', 'BPS Kabupaten Kerinci');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('5', '1502', 'BPS Kabupaten Merangin');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('5', '1503', 'BPS Kabupaten Sarolangun');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('5', '1504', 'BPS Kabupaten Batang Hari');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('5', '1505', 'BPS Kabupaten Muaro Jambi');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('5', '1506', 'BPS Kabupaten Tanjung Jabung Timur');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('5', '1507', 'BPS Kabupaten Tanjung Jabung Barat');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('5', '1508', 'BPS Kabupaten Tebo');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('5', '1509', 'BPS Kabupaten Bungo');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('5', '1571', 'BPS Kota Jambi');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('5', '1572', 'BPS Kota Sungai Penuh');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('6', '1600', 'BPS Provinsi Sumatera Selatan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('6', '1601', 'BPS Kabupaten Ogan Komering Ulu');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('6', '1602', 'BPS Kabupaten Ogan Komering Ilir');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('6', '1603', 'BPS Kabupaten Muara Enim');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('6', '1604', 'BPS Kabupaten Lahat');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('6', '1605', 'BPS Kabupaten Musi Rawas');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('6', '1606', 'BPS Kabupaten Musi Banyuasin');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('6', '1607', 'BPS Kabupaten Banyu Asin');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('6', '1608', 'BPS Kabupaten Ogan Komering Ulu Selatan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('6', '1609', 'BPS Kabupaten Ogan Komering Ulu Timur');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('6', '1610', 'BPS Kabupaten Ogan Ilir');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('6', '1611', 'BPS Kabupaten Empat Lawang');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('6', '1612', 'BPS Kabupaten Penukal Abab Lematang Ilir');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('6', '1613', 'BPS Kabupaten Musi Rawas Utara');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('6', '1671', 'BPS Kota Palembang');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('6', '1672', 'BPS Kota Prabumulih');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('6', '1673', 'BPS Kota Pagar Alam');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('6', '1674', 'BPS Kota Lubuklinggau');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('7', '1700', 'BPS Provinsi Bengkulu');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('7', '1701', 'BPS Kabupaten Bengkulu Selatan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('7', '1702', 'BPS Kabupaten Rejang Lebong');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('7', '1703', 'BPS Kabupaten Bengkulu Utara');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('7', '1704', 'BPS Kabupaten Kaur');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('7', '1705', 'BPS Kabupaten Seluma');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('7', '1706', 'BPS Kabupaten Mukomuko');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('7', '1707', 'BPS Kabupaten Lebong');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('7', '1708', 'BPS Kabupaten Kepahiang');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('7', '1709', 'BPS Kabupaten Bengkulu Tengah');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('7', '1771', 'BPS Kota Bengkulu');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('8', '1800', 'BPS Provinsi Lampung');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('8', '1801', 'BPS Kabupaten Lampung Barat');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('8', '1802', 'BPS Kabupaten Tanggamus');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('8', '1803', 'BPS Kabupaten Lampung Selatan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('8', '1804', 'BPS Kabupaten Lampung Timur');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('8', '1805', 'BPS Kabupaten Lampung Tengah');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('8', '1806', 'BPS Kabupaten Lampung Utara');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('8', '1807', 'BPS Kabupaten Way Kanan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('8', '1808', 'BPS Kabupaten Tulangbawang');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('8', '1809', 'BPS Kabupaten Pesawaran');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('8', '1810', 'BPS Kabupaten Pringsewu');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('8', '1811', 'BPS Kabupaten Mesuji');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('8', '1812', 'BPS Kabupaten Tulang Bawang Barat');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('8', '1813', 'BPS Kabupaten Pesisir Barat');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('8', '1871', 'BPS Kota Bandar Lampung');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('8', '1872', 'BPS Kota Metro');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('9', '1900', 'BPS Provinsi Kep. Bangka Belitung');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('9', '1901', 'BPS Kabupaten Bangka');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('9', '1902', 'BPS Kabupaten Belitung');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('9', '1903', 'BPS Kabupaten Bangka Barat');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('9', '1904', 'BPS Kabupaten Bangka Tengah');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('9', '1905', 'BPS Kabupaten Bangka Selatan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('9', '1906', 'BPS Kabupaten Belitung Timur');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('9', '1971', 'BPS Kota Pangkalpinang');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('10', '2100', 'BPS Provinsi Kep. Riau');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('10', '2101', 'BPS Kabupaten Karimun');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('10', '2102', 'BPS Kabupaten Bintan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('10', '2103', 'BPS Kabupaten Natuna');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('10', '2104', 'BPS Kabupaten Lingga');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('10', '2105', 'BPS Kabupaten Kepulauan Anambas');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('10', '2171', 'BPS Kota B A T A M');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('10', '2172', 'BPS Kota Tanjung Pinang');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('11', '3100', 'BPS Provinsi Dki Jakarta');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('11', '3101', 'BPS Kabupaten Kepulauan Seribu');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('11', '3171', 'BPS Kota Jakarta Selatan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('11', '3172', 'BPS Kota Jakarta Timur');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('11', '3173', 'BPS Kota Jakarta Pusat');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('11', '3174', 'BPS Kota Jakarta Barat');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('11', '3175', 'BPS Kota Jakarta Utara');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('12', '3200', 'BPS Provinsi Jawa Barat');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('12', '3201', 'BPS Kabupaten Bogor');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('12', '3202', 'BPS Kabupaten Sukabumi');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('12', '3203', 'BPS Kabupaten Cianjur');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('12', '3204', 'BPS Kabupaten Bandung');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('12', '3205', 'BPS Kabupaten Garut');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('12', '3206', 'BPS Kabupaten Tasikmalaya');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('12', '3207', 'BPS Kabupaten Ciamis');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('12', '3208', 'BPS Kabupaten Kuningan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('12', '3209', 'BPS Kabupaten Cirebon');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('12', '3210', 'BPS Kabupaten Majalengka');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('12', '3211', 'BPS Kabupaten Sumedang');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('12', '3212', 'BPS Kabupaten Indramayu');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('12', '3213', 'BPS Kabupaten Subang');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('12', '3214', 'BPS Kabupaten Purwakarta');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('12', '3215', 'BPS Kabupaten Karawang');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('12', '3216', 'BPS Kabupaten Bekasi');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('12', '3217', 'BPS Kabupaten Bandung Barat');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('12', '3218', 'BPS Kabupaten Pangandaran');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('12', '3271', 'BPS Kota Bogor');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('12', '3272', 'BPS Kota Sukabumi');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('12', '3273', 'BPS Kota Bandung');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('12', '3274', 'BPS Kota Cirebon');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('12', '3275', 'BPS Kota Bekasi');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('12', '3276', 'BPS Kota Depok');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('12', '3277', 'BPS Kota Cimahi');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('12', '3278', 'BPS Kota Tasikmalaya');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('12', '3279', 'BPS Kota Banjar');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('13', '3300', 'BPS Provinsi Jawa Tengah');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('13', '3301', 'BPS Kabupaten Cilacap');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('13', '3302', 'BPS Kabupaten Banyumas');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('13', '3303', 'BPS Kabupaten Purbalingga');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('13', '3304', 'BPS Kabupaten Banjarnegara');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('13', '3305', 'BPS Kabupaten Kebumen');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('13', '3306', 'BPS Kabupaten Purworejo');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('13', '3307', 'BPS Kabupaten Wonosobo');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('13', '3308', 'BPS Kabupaten Magelang');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('13', '3309', 'BPS Kabupaten Boyolali');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('13', '3310', 'BPS Kabupaten Klaten');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('13', '3311', 'BPS Kabupaten Sukoharjo');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('13', '3312', 'BPS Kabupaten Wonogiri');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('13', '3313', 'BPS Kabupaten Karanganyar');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('13', '3314', 'BPS Kabupaten Sragen');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('13', '3315', 'BPS Kabupaten Grobogan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('13', '3316', 'BPS Kabupaten Blora');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('13', '3317', 'BPS Kabupaten Rembang');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('13', '3318', 'BPS Kabupaten Pati');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('13', '3319', 'BPS Kabupaten Kudus');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('13', '3320', 'BPS Kabupaten Jepara');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('13', '3321', 'BPS Kabupaten Demak');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('13', '3322', 'BPS Kabupaten Semarang');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('13', '3323', 'BPS Kabupaten Temanggung');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('13', '3324', 'BPS Kabupaten Kendal');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('13', '3325', 'BPS Kabupaten Batang');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('13', '3326', 'BPS Kabupaten Pekalongan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('13', '3327', 'BPS Kabupaten Pemalang');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('13', '3328', 'BPS Kabupaten Tegal');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('13', '3329', 'BPS Kabupaten Brebes');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('13', '3371', 'BPS Kota Magelang');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('13', '3372', 'BPS Kota Surakarta');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('13', '3373', 'BPS Kota Salatiga');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('13', '3374', 'BPS Kota Semarang');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('13', '3375', 'BPS Kota Pekalongan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('13', '3376', 'BPS Kota Tegal');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('14', '3400', 'BPS Provinsi Di Yogyakarta');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('14', '3401', 'BPS Kabupaten Kulon Progo');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('14', '3402', 'BPS Kabupaten Bantul');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('14', '3403', 'BPS Kabupaten Gunungkidul');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('14', '3404', 'BPS Kabupaten Sleman');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('14', '3471', 'BPS Kota Yogyakarta');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('15', '3500', 'BPS Provinsi Jawa Timur');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('15', '3501', 'BPS Kabupaten Pacitan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('15', '3502', 'BPS Kabupaten Ponorogo');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('15', '3503', 'BPS Kabupaten Trenggalek');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('15', '3504', 'BPS Kabupaten Tulungagung');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('15', '3505', 'BPS Kabupaten Blitar');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('15', '3506', 'BPS Kabupaten Kediri');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('15', '3507', 'BPS Kabupaten Malang');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('15', '3508', 'BPS Kabupaten Lumajang');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('15', '3509', 'BPS Kabupaten Jember');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('15', '3510', 'BPS Kabupaten Banyuwangi');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('15', '3511', 'BPS Kabupaten Bondowoso');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('15', '3512', 'BPS Kabupaten Situbondo');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('15', '3513', 'BPS Kabupaten Probolinggo');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('15', '3514', 'BPS Kabupaten Pasuruan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('15', '3515', 'BPS Kabupaten Sidoarjo');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('15', '3516', 'BPS Kabupaten Mojokerto');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('15', '3517', 'BPS Kabupaten Jombang');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('15', '3518', 'BPS Kabupaten Nganjuk');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('15', '3519', 'BPS Kabupaten Madiun');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('15', '3520', 'BPS Kabupaten Magetan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('15', '3521', 'BPS Kabupaten Ngawi');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('15', '3522', 'BPS Kabupaten Bojonegoro');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('15', '3523', 'BPS Kabupaten Tuban');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('15', '3524', 'BPS Kabupaten Lamongan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('15', '3525', 'BPS Kabupaten Gresik');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('15', '3526', 'BPS Kabupaten Bangkalan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('15', '3527', 'BPS Kabupaten Sampang');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('15', '3528', 'BPS Kabupaten Pamekasan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('15', '3529', 'BPS Kabupaten Sumenep');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('15', '3571', 'BPS Kota Kediri');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('15', '3572', 'BPS Kota Blitar');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('15', '3573', 'BPS Kota Malang');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('15', '3574', 'BPS Kota Probolinggo');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('15', '3575', 'BPS Kota Pasuruan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('15', '3576', 'BPS Kota Mojokerto');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('15', '3577', 'BPS Kota Madiun');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('15', '3578', 'BPS Kota Surabaya');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('15', '3579', 'BPS Kota Batu');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('16', '3600', 'BPS Provinsi Banten');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('16', '3601', 'BPS Kabupaten Pandeglang');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('16', '3602', 'BPS Kabupaten Lebak');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('16', '3603', 'BPS Kabupaten Tangerang');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('16', '3604', 'BPS Kabupaten Serang');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('16', '3671', 'BPS Kota Tangerang');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('16', '3672', 'BPS Kota Cilegon');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('16', '3673', 'BPS Kota Serang');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('16', '3674', 'BPS Kota Tangerang Selatan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('17', '5100', 'BPS Provinsi Bali');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('17', '5101', 'BPS Kabupaten Jembrana');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('17', '5102', 'BPS Kabupaten Tabanan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('17', '5103', 'BPS Kabupaten Badung');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('17', '5104', 'BPS Kabupaten Gianyar');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('17', '5105', 'BPS Kabupaten Klungkung');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('17', '5106', 'BPS Kabupaten Bangli');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('17', '5107', 'BPS Kabupaten Karangasem');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('17', '5108', 'BPS Kabupaten Buleleng');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('17', '5171', 'BPS Kota Denpasar');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('18', '5200', 'BPS Provinsi Nusa Tenggara Barat');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('18', '5201', 'BPS Kabupaten Lombok Barat');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('18', '5202', 'BPS Kabupaten Lombok Tengah');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('18', '5203', 'BPS Kabupaten Lombok Timur');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('18', '5204', 'BPS Kabupaten Sumbawa');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('18', '5205', 'BPS Kabupaten Dompu');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('18', '5206', 'BPS Kabupaten Bima');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('18', '5207', 'BPS Kabupaten Sumbawa Barat');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('18', '5208', 'BPS Kabupaten Lombok Utara');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('18', '5271', 'BPS Kota Mataram');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('18', '5272', 'BPS Kota Bima');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('19', '5300', 'BPS Provinsi Nusa Tenggara Timur');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('19', '5301', 'BPS Kabupaten Sumba Barat');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('19', '5302', 'BPS Kabupaten Sumba Timur');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('19', '5303', 'BPS Kabupaten Kupang');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('19', '5304', 'BPS Kabupaten Timor Tengah Selatan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('19', '5305', 'BPS Kabupaten Timor Tengah Utara');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('19', '5306', 'BPS Kabupaten Belu');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('19', '5307', 'BPS Kabupaten Alor');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('19', '5308', 'BPS Kabupaten Lembata');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('19', '5309', 'BPS Kabupaten Flores Timur');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('19', '5310', 'BPS Kabupaten Sikka');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('19', '5311', 'BPS Kabupaten Ende');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('19', '5312', 'BPS Kabupaten Ngada');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('19', '5313', 'BPS Kabupaten Manggarai');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('19', '5314', 'BPS Kabupaten Rote Ndao');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('19', '5315', 'BPS Kabupaten Manggarai Barat');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('19', '5316', 'BPS Kabupaten Sumba Tengah');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('19', '5317', 'BPS Kabupaten Sumba Barat Daya');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('19', '5318', 'BPS Kabupaten Nagekeo');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('19', '5319', 'BPS Kabupaten Manggarai Timur');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('19', '5320', 'BPS Kabupaten Sabu Raijua');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('19', '5321', 'BPS Kabupaten Malaka');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('19', '5371', 'BPS Kota Kupang');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('20', '6100', 'BPS Provinsi Kalimantan Barat');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('20', '6101', 'BPS Kabupaten Sambas');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('20', '6102', 'BPS Kabupaten Bengkayang');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('20', '6103', 'BPS Kabupaten Landak');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('20', '6104', 'BPS Kabupaten Mempawah');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('20', '6105', 'BPS Kabupaten Sanggau');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('20', '6106', 'BPS Kabupaten Ketapang');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('20', '6107', 'BPS Kabupaten Sintang');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('20', '6108', 'BPS Kabupaten Kapuas Hulu');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('20', '6109', 'BPS Kabupaten Sekadau');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('20', '6110', 'BPS Kabupaten Melawi');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('20', '6111', 'BPS Kabupaten Kayong Utara');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('20', '6112', 'BPS Kabupaten Kubu Raya');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('20', '6171', 'BPS Kota Pontianak');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('20', '6172', 'BPS Kota Singkawang');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('21', '6200', 'BPS Provinsi Kalimantan Tengah');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('21', '6201', 'BPS Kabupaten Kotawaringin Barat');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('21', '6202', 'BPS Kabupaten Kotawaringin Timur');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('21', '6203', 'BPS Kabupaten Kapuas');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('21', '6204', 'BPS Kabupaten Barito Selatan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('21', '6205', 'BPS Kabupaten Barito Utara');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('21', '6206', 'BPS Kabupaten Sukamara');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('21', '6207', 'BPS Kabupaten Lamandau');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('21', '6208', 'BPS Kabupaten Seruyan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('21', '6209', 'BPS Kabupaten Katingan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('21', '6210', 'BPS Kabupaten Pulang Pisau');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('21', '6211', 'BPS Kabupaten Gunung Mas');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('21', '6212', 'BPS Kabupaten Barito Timur');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('21', '6213', 'BPS Kabupaten Murung Raya');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('21', '6271', 'BPS Kota Palangka Raya');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('22', '6300', 'BPS Provinsi Kalimantan Selatan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('22', '6301', 'BPS Kabupaten Tanah Laut');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('22', '6302', 'BPS Kabupaten Kotabaru');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('22', '6303', 'BPS Kabupaten Banjar');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('22', '6304', 'BPS Kabupaten Barito Kuala');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('22', '6305', 'BPS Kabupaten Tapin');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('22', '6306', 'BPS Kabupaten Hulu Sungai Selatan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('22', '6307', 'BPS Kabupaten Hulu Sungai Tengah');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('22', '6308', 'BPS Kabupaten Hulu Sungai Utara');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('22', '6309', 'BPS Kabupaten Tabalong');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('22', '6310', 'BPS Kabupaten Tanah Bumbu');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('22', '6311', 'BPS Kabupaten Balangan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('22', '6371', 'BPS Kota Banjarmasin');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('22', '6372', 'BPS Kota Banjar Baru');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('23', '6400', 'BPS Provinsi Kalimantan Timur');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('23', '6401', 'BPS Kabupaten Paser');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('23', '6402', 'BPS Kabupaten Kutai Barat');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('23', '6403', 'BPS Kabupaten Kutai Kartanegara');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('23', '6404', 'BPS Kabupaten Kutai Timur');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('23', '6405', 'BPS Kabupaten Berau');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('23', '6409', 'BPS Kabupaten Penajam Paser Utara');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('23', '6411', 'BPS Kabupaten Mahakam Hulu');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('23', '6471', 'BPS Kota Balikpapan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('23', '6472', 'BPS Kota Samarinda');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('23', '6474', 'BPS Kota Bontang');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('24', '6500', 'BPS Provinsi Kalimantan Utara');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('24', '6501', 'BPS Kabupaten Malinau');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('24', '6502', 'BPS Kabupaten Bulungan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('24', '6503', 'BPS Kabupaten Tana Tidung');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('24', '6504', 'BPS Kabupaten Nunukan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('24', '6571', 'BPS Kota Tarakan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('25', '7100', 'BPS Provinsi Sulawesi Utara');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('25', '7101', 'BPS Kabupaten Bolaang Mongondow');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('25', '7102', 'BPS Kabupaten Minahasa');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('25', '7103', 'BPS Kabupaten Kepulauan Sangihe');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('25', '7104', 'BPS Kabupaten Kepulauan Talaud');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('25', '7105', 'BPS Kabupaten Minahasa Selatan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('25', '7106', 'BPS Kabupaten Minahasa Utara');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('25', '7107', 'BPS Kabupaten Bolaang Mongondow Utara');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('25', '7108', 'BPS Kabupaten Siau Tagulandang Biaro');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('25', '7109', 'BPS Kabupaten Minahasa Tenggara');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('25', '7110', 'BPS Kabupaten Bolaang Mongondow Selatan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('25', '7111', 'BPS Kabupaten Bolaang Mongondow Timur');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('25', '7171', 'BPS Kota Manado');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('25', '7172', 'BPS Kota Bitung');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('25', '7173', 'BPS Kota Tomohon');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('25', '7174', 'BPS Kota Kotamobagu');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('26', '7200', 'BPS Provinsi Sulawesi Tengah');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('26', '7201', 'BPS Kabupaten Banggai Kepulauan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('26', '7202', 'BPS Kabupaten Banggai');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('26', '7203', 'BPS Kabupaten Morowali');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('26', '7204', 'BPS Kabupaten Poso');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('26', '7205', 'BPS Kabupaten Donggala');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('26', '7206', 'BPS Kabupaten Toli-toli');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('26', '7207', 'BPS Kabupaten Buol');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('26', '7208', 'BPS Kabupaten Parigi Moutong');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('26', '7209', 'BPS Kabupaten Tojo Una-una');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('26', '7210', 'BPS Kabupaten Sigi');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('26', '7211', 'BPS Kabupaten Banggai Laut');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('26', '7212', 'BPS Kabupaten Morowali Utara');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('26', '7271', 'BPS Kota Palu');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('27', '7300', 'BPS Provinsi Sulawesi Selatan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('27', '7301', 'BPS Kabupaten Kepulauan Selayar');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('27', '7302', 'BPS Kabupaten Bulukumba');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('27', '7303', 'BPS Kabupaten Bantaeng');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('27', '7304', 'BPS Kabupaten Jeneponto');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('27', '7305', 'BPS Kabupaten Takalar');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('27', '7306', 'BPS Kabupaten Gowa');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('27', '7307', 'BPS Kabupaten Sinjai');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('27', '7308', 'BPS Kabupaten Maros');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('27', '7309', 'BPS Kabupaten Pangkajene Dan Kepulauan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('27', '7310', 'BPS Kabupaten Barru');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('27', '7311', 'BPS Kabupaten Bone');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('27', '7312', 'BPS Kabupaten Soppeng');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('27', '7313', 'BPS Kabupaten Wajo');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('27', '7314', 'BPS Kabupaten Sidenreng Rappang');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('27', '7315', 'BPS Kabupaten Pinrang');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('27', '7316', 'BPS Kabupaten Enrekang');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('27', '7317', 'BPS Kabupaten Luwu');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('27', '7318', 'BPS Kabupaten Tana Toraja');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('27', '7322', 'BPS Kabupaten Luwu Utara');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('27', '7325', 'BPS Kabupaten Luwu Timur');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('27', '7326', 'BPS Kabupaten Toraja Utara');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('27', '7371', 'BPS Kota Makassar');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('27', '7372', 'BPS Kota Parepare');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('27', '7373', 'BPS Kota Palopo');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('28', '7400', 'BPS Provinsi Sulawesi Tenggara');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('28', '7401', 'BPS Kabupaten Buton');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('28', '7402', 'BPS Kabupaten Muna');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('28', '7403', 'BPS Kabupaten Konawe');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('28', '7404', 'BPS Kabupaten Kolaka');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('28', '7405', 'BPS Kabupaten Konawe Selatan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('28', '7406', 'BPS Kabupaten Bombana');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('28', '7407', 'BPS Kabupaten Wakatobi');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('28', '7408', 'BPS Kabupaten Kolaka Utara');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('28', '7409', 'BPS Kabupaten Buton Utara');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('28', '7410', 'BPS Kabupaten Konawe Utara');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('28', '7411', 'BPS Kabupaten Kolaka Timur');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('28', '7412', 'BPS Kabupaten Konawe Kepulauan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('28', '7413', 'BPS Kabupaten Muna Barat');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('28', '7414', 'BPS Kabupaten Buton Tengah');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('28', '7415', 'BPS Kabupaten Buton Selatan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('28', '7471', 'BPS Kota Kendari');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('28', '7472', 'BPS Kota Baubau');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('29', '7500', 'BPS Provinsi Gorontalo');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('29', '7501', 'BPS Kabupaten Boalemo');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('29', '7502', 'BPS Kabupaten Gorontalo');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('29', '7503', 'BPS Kabupaten Pohuwato');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('29', '7504', 'BPS Kabupaten Bone Bolango');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('29', '7505', 'BPS Kabupaten Gorontalo Utara');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('29', '7571', 'BPS Kota Gorontalo');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('30', '7600', 'BPS Provinsi Sulawesi Barat');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('30', '7601', 'BPS Kabupaten Majene');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('30', '7602', 'BPS Kabupaten Polewali Mandar');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('30', '7603', 'BPS Kabupaten Mamasa');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('30', '7604', 'BPS Kabupaten Mamuju');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('30', '7605', 'BPS Kabupaten Pasangkayu');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('30', '7606', 'BPS Kabupaten Mamuju Tengah');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('31', '8100', 'BPS Provinsi Maluku');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('31', '8101', 'BPS Kabupaten Kepulauan Tanimbar');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('31', '8102', 'BPS Kabupaten Maluku Tenggara');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('31', '8103', 'BPS Kabupaten Maluku Tengah');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('31', '8104', 'BPS Kabupaten Buru');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('31', '8105', 'BPS Kabupaten Kepulauan Aru');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('31', '8106', 'BPS Kabupaten Seram Bagian Barat');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('31', '8107', 'BPS Kabupaten Seram Bagian Timur');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('31', '8108', 'BPS Kabupaten Maluku Barat Daya');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('31', '8109', 'BPS Kabupaten Buru Selatan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('31', '8171', 'BPS Kota Ambon');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('31', '8172', 'BPS Kota Tual');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('32', '8200', 'BPS Provinsi Maluku Utara');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('32', '8201', 'BPS Kabupaten Halmahera Barat');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('32', '8202', 'BPS Kabupaten Halmahera Tengah');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('32', '8203', 'BPS Kabupaten Kepulauan Sula');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('32', '8204', 'BPS Kabupaten Halmahera Selatan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('32', '8205', 'BPS Kabupaten Halmahera Utara');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('32', '8206', 'BPS Kabupaten Halmahera Timur');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('32', '8207', 'BPS Kabupaten Pulau Morotai');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('32', '8208', 'BPS Kabupaten Pulau Taliabu');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('32', '8271', 'BPS Kota Ternate');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('32', '8272', 'BPS Kota Tidore Kepulauan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('33', '9100', 'BPS Provinsi Papua Barat');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('33', '9101', 'BPS Kabupaten Fakfak');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('33', '9102', 'BPS Kabupaten Kaimana');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('33', '9103', 'BPS Kabupaten Teluk Wondama');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('33', '9104', 'BPS Kabupaten Teluk Bintuni');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('33', '9105', 'BPS Kabupaten Manokwari');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('33', '9106', 'BPS Kabupaten Sorong Selatan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('33', '9107', 'BPS Kabupaten Sorong');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('33', '9108', 'BPS Kabupaten Raja Ampat');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('33', '9109', 'BPS Kabupaten Tambrauw');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('33', '9110', 'BPS Kabupaten Maybrat');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('33', '9111', 'BPS Kabupaten Manokwari Selatan');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('33', '9112', 'BPS Kabupaten Pegunungan Arfak');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('33', '9171', 'BPS Kota Sorong');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('34', '9400', 'BPS Provinsi Papua');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('34', '9401', 'BPS Kabupaten Merauke');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('34', '9402', 'BPS Kabupaten Jayawijaya');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('34', '9403', 'BPS Kabupaten Jayapura');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('34', '9404', 'BPS Kabupaten Nabire');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('34', '9408', 'BPS Kabupaten Kepulauan Yapen');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('34', '9409', 'BPS Kabupaten Biak Numfor');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('34', '9410', 'BPS Kabupaten Paniai');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('34', '9411', 'BPS Kabupaten Puncak Jaya');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('34', '9412', 'BPS Kabupaten Mimika');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('34', '9413', 'BPS Kabupaten Boven Digoel');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('34', '9414', 'BPS Kabupaten Mappi');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('34', '9415', 'BPS Kabupaten Asmat');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('34', '9416', 'BPS Kabupaten Yahukimo');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('34', '9417', 'BPS Kabupaten Pegunungan Bintang');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('34', '9418', 'BPS Kabupaten Tolikara');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('34', '9419', 'BPS Kabupaten Sarmi');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('34', '9420', 'BPS Kabupaten Keerom');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('34', '9426', 'BPS Kabupaten Waropen');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('34', '9427', 'BPS Kabupaten Supiori');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('34', '9428', 'BPS Kabupaten Mamberamo Raya');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('34', '9429', 'BPS Kabupaten Nduga');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('34', '9430', 'BPS Kabupaten Lanny Jaya');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('34', '9431', 'BPS Kabupaten Mamberamo Tengah');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('34', '9432', 'BPS Kabupaten Yalimo');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('34', '9433', 'BPS Kabupaten Puncak');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('34', '9434', 'BPS Kabupaten Dogiyai');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('34', '9435', 'BPS Kabupaten Intan Jaya');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('34', '9436', 'BPS Kabupaten Deiyai');
INSERT INTO formasi (provinsi_id, kode_satker, nama_satuan_kerja) VALUES ('34', '9471', 'BPS Kota Jayapura');
